{
 "title": "MongoDB Oplog Details",
 "tags": [
  "Percona",
  "MongoDB"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Oplog Recovery Window", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Oplog Recovery Window - $node_name",
   "type": "timeseries",
   "description": "This panel provides details about your recovery window over a time interval based on your oplog activities. It coordinates with replication and backup activities.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "node_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time()-avg by (instance) (mongodb_mongod_replset_oplog_tail_timestamp{instance=~\"$node_name\"})",
     "legendFormat": "Now to End"
    },
    {
     "expr": "avg by (instance) (mongodb_mongod_replset_oplog_head_timestamp{instance=~\"$node_name\"}-mongodb_mongod_replset_oplog_tail_timestamp{instance=~\"$node_name\"})",
     "legendFormat": "Oplog Range"
    }
   ]
  },
  { "title": "Oplog Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Oplog Buffered Operations",
   "type": "timeseries",
   "description": "Repl buffer ops applied per sec.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_ss_metrics_repl_buffer_apply_count{instance=~\"$node_name\"}) or avg by (instance) (mongodb_mongod_metrics_repl_buffer_count{instance=~\"$node_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "timeseries",
   "description": "Provides information related to the number of getmore commands erlated to the local db oplog.rs collection",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{instance=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Processing Time - $node_name",
   "type": "timeseries",
   "description": "Times spent per second A) pre-loading oplog ops into parallel-executable batches B) Times spent pre-loading index values and C) repl batch apply phase.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "repeat": "node_name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity - $node_name",
   "type": "timeseries",
   "description": "Provides info on the current usage and actual size of the replication buffer as defined by the maximum oplog size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "node_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_ss_metrics_repl_buffer_apply_sizeBytes{instance=~\"$node_name\"}) or avg by (instance) (mongodb_mongod_metrics_repl_buffer_size_bytes{instance=~\"$node_name\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (instance) (mongodb_ss_metrics_repl_buffer_apply_maxSizeBytes{instance=~\"$node_name\"}) or avg by (service_name) (mongodb_mongod_metrics_repl_buffer_max_size_bytes{instance=~\"$node_name\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Oplog Operations - [$node_name]",
   "type": "timeseries",
   "description": "Provides information on the number of write operations recorded in the oplog collection over a period of time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "repeat": "node_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_mongod_metrics_repl_apply_ops_total{instance=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_ops_total{instance=~\"$node_name\"}[5m]))",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  { "title": "Oplog Generation Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Oplog GB/Hour",
   "type": "timeseries",
   "description": "The average amount of data in GB that the PRIMARY generate per hour",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "repeat": "node_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_oplog_stats_wt_cache_bytes_written_from_cache{instance=~\"$node_name\"}[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}