{
 "title": "MongoDB Collections Overview",
 "tags": [
  "Percona",
  "MongoDB"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "rs_nm",
    "label": "rs_nm",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state, set)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up, instance)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(mongodb_top_commands_count{instance=~\"$node_name\"}, database)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Datasize", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 5 Databases By Size",
   "type": "timeseries",
   "description": "Provides the names and sizes of the 5 largest databases in an instance/cluster. Data showing only from Primary node in replica set.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(database) (topk(5, mongodb_dbstats_dataSize{ rs_nm=~\"$rs_nm\", instance=~\"$node_name\"}))",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Collections in Database ($database)",
   "type": "stat",
   "description": "Provides the number of collections in the selected databases",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mongodb_top_commands_time{database=~\"$database\",instance=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Indexes in Database ($database)",
   "type": "stat",
   "description": "Provides the number of indexes in the selected databases",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_indexes{database=~\"$database\",instance=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Avg Object Size in Database ($database)",
   "type": "timeseries",
   "description": "Average size of each document in bytes. dataSize divided by number of documents",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_dbstats_avgObjSize{ instance=~\"$node_name\", database=~\"$database\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Index Size in Database ($database)",
   "type": "timeseries",
   "description": "Total size of all indexes in a given database",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_dbstats_indexSize{database=~\"$database\", instance=~\"$node_name\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Data Size for Database ($database)",
   "type": "timeseries",
   "description": "Total size of uncompressed data in a database in bytes. May be larger than storageSize due to WT compression. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_dbstats_dataSize{database=~\"$database\",instance=~\"$node_name\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Instance Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top 5 Hottest Collections by Read  (Total)",
   "type": "table",
   "description": "Show summary information on the top 5 collections that are most frequently read.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk (5,sum by (database, collection) (mongodb_top_queries_count{database =~ \"$database\",instance=~\"$node_name\"}))"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Write (Total)",
   "type": "table",
   "description": "Show summary information on the top 5 collections that are most frequently written to (insert, update, delete, etc.).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum by (database, collection) (mongodb_top_insert_count{database =~ \"$database\",instance=~\"$node_name\"}) + sum by (database, collection) (mongodb_top_remove_count{database =~ \"$database\",instance=~\"$node_name\"}) + sum by (database, collection) (mongodb_top_update_count{database =~ \"$database\",instance=~\"$node_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Read (Rate)",
   "type": "bargauge",
   "description": "Show the 5 collections that are most frequently read.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (database, collection) (rate(mongodb_top_queries_count{database =~ \"$database\",instance=~\"$node_name\"}[$interval])))",
     "legendFormat": "{{ database }}.{{ collection }}"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Write (Rate)",
   "type": "bargauge",
   "description": "Show the 5 collections that are most frequently written to (insert, update, delete, etc.).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (database, collection) ((rate(mongodb_top_insert_count{database =~ \"$database\",instance=~\"$node_name\"}[$interval])) + (rate(mongodb_top_remove_count{database =~ \"$database\",instance=~\"$node_name\"}[$interval])) + (rate(mongodb_top_update_count{database =~ \"$database\",instance=~\"$node_name\"}[$interval]))))",
     "legendFormat": "{{ database }}.{{ collection }}"
    }
   ]
  },
  { "title": "Database Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Collections statistics  for $database (rate)",
   "type": "timeseries",
   "description": "Provides information on the rate of activity against the database then breaks down into activity type over the selected time period",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (rate(mongodb_top_commands_count{database=~\"$database\",instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Commands - {{database}}"
    },
    {
     "expr": "sum by (database) (rate(mongodb_top_insert_count {database=~\"$database\",instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Insert - {{database}}"
    },
    {
     "expr": "sum by (database) (rate(mongodb_top_update_count {database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Update - {{database}}"
    },
    {
     "expr": "sum by (database) (rate(mongodb_top_remove_count {database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Remove - {{database}}"
    },
    {
     "expr": "sum by (database) (rate(mongodb_top_getmore_count {database=~\"$database\",instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Getmore - {{database}}"
    },
    {
     "expr": "sum by (database) (rate(mongodb_top_queries_count {rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Queries - {{database}}"
    }
   ]
  },
  {
   "title": "Collections statistics  for $database (summary)",
   "type": "timeseries",
   "description": "Provides summary information on the activity running against the database then breaks down into activity type over the selected time period",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (increase(mongodb_top_commands_count {rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Commands - {{database}}"
    },
    {
     "expr": "sum by (database) (increase(mongodb_top_insert_count {rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Insert - {{database}}"
    },
    {
     "expr": "sum by (database) (increase(mongodb_top_update_count {rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Update - {{database}}"
    },
    {
     "expr": "sum by (database) (increase(mongodb_top_remove_count {rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Remove - {{database}}"
    },
    {
     "expr": "sum by (database) (increase(mongodb_top_getmore_count {rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Getmore - {{database}}"
    },
    {
     "expr": "sum by (database) (increase(mongodb_top_queries_count {rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"}[$interval]))",
     "legendFormat": "Queries - {{database}}"
    }
   ]
  },
  {
   "title": "Collections statistics  $database",
   "type": "table",
   "description": "Provides totals for each activity type hitting a database for collections",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "repeat": "database",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (collection) (mongodb_top_queries_count {  rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_insert_count {  rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_remove_count {  rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_update_count{  rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_getmore_count {  rs_nm=~\"$rs_nm\", database=~\"$database\", instance=~\"$node_name\"})"
    }
   ]
  }
 ]
}