{
 "title": "MongoDB Instances Overview",
 "tags": [
  "MongoDB",
  "Percona",
  "Services"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sharded Clusters",
   "type": "stat",
   "description": "Number of Sharded Clusters",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (\n  mongodb_mongos_sharding_shards_total{ }\n))"
    }
   ]
  },
  {
   "title": "Replica Sets",
   "type": "stat",
   "description": "Number of Replica Sets that are not part of a Sharded Cluster",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (\n  mongodb_myState{  cl_role=\"\"}\n)) or vector(0)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "description": "Total number of MongoDB processes monitored (mongod + mongos)",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (service_name)(mongodb_up{  instance=~\"$node_name\"}))"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "description": "Percent of time each Cluster/Replica Set had a primary",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg by (replset) (\n  avg_over_time((mongodb_mongod_replset_my_state{} == bool 1)[$__range:])\n) * 100"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "stat",
   "description": "Total number of read/write operations in the selected Cluster/Replica Set",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\",type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\",type!=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\",type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Docs Accessed",
   "type": "stat",
   "description": "Documents inserted, updated, deleted or returned per second in the selected Cluster/Replica Set",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "docs/s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Time Since Election",
   "type": "stat",
   "description": "Time since the most recent election in the selected Cluster/Replica Set",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_election_date{})"
    }
   ]
  },
  {
   "title": "Min Uptime",
   "type": "stat",
   "description": "Minimum uptime between all processes (mongod and mongos) in the selected Cluster/Replica Set",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(mongodb_instance_uptime_seconds{ instance=~\"$node_name\"})"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node Summary",
   "type": "piechart",
   "description": "mongod servers registered with PMM server",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  max by(member_idx) (mongodb_members_state{instance=~\"$node_name\"}\n    == 1)\n  or\n  max by(member_idx) (mongodb_members_state{instance=~\"$node_name\"}\n    == 2)\n  or\n  max by(member_idx) (mongodb_members_state{ instance=~\"$node_name\"}\n    == 7) \n)",
     "legendFormat": "OK"
    },
    {
     "expr": "count(\n  max by(member_idx) (mongodb_members_state{ instance=~\"$node_name\"}\n    != 1)\n  and\n  max by(member_idx) (mongodb_members_state{ instance=~\"$node_name\"}\n    != 2)\n  and\n  max by(member_idx) (mongodb_members_state{ instance=~\"$node_name\"}\n    != 7)  \n)",
     "legendFormat": "CHECK"
    }
   ]
  },
  {
   "title": "Replica Set Status",
   "type": "grafana-polystat-panel",
   "description": "Click on each Replica Set to go to the details page",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "max by (rs_nm)(mongodb_members_state{instance=~\"$node_name\",instance=~\"$node_name\",cl_role=\"\"} != 7) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sharded Cluster Status",
   "type": "grafana-polystat-panel",
   "description": "Click on each Cluster to go to the details page",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "max by(cluster) (\n  max by (rs_nm, cluster) (\n    mongodb_members_state{instance=~\"$node_name\"} != 7\n  )\n)\nand on(cluster)\n  mongodb_mongos_sharding_shards_total{ }",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Summary",
   "type": "piechart",
   "description": "Mongos Routers registered with PMM Server",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values( \"state\", min by (instance)(mongodb_up))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Status",
   "type": "grafana-polystat-panel",
   "description": "Click on each Mongos Router to go to the details page",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "min by (service_name)(mongodb_up{cluster_role=\"mongos\",instance=~\"$node_name\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Connections Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Connections",
     "type": "timeseries",
     "description": "TCP connections (Incoming) in mongod processes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((max_over_time(mongodb_mongod_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{ instance=~\"$node_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{ instance=~\"$node_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{ instance=~\"$node_name\", state=\"current\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{ instance=~\"$node_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{ instance=~\"$node_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{ instance=~\"$node_name\", state=\"current\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mongodb_mongod_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{ instance=~\"$node_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{ instance=~\"$node_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{ instance=~\"$node_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{ instance=~\"$node_name\", state=\"current\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Opcounters Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Command Operations",
     "type": "timeseries",
     "description": "The average rate of commands performed per second over the selected sample period",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,sum by (service_name) (rate(mongodb_mongod_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Command Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{instance=~\"$node_name\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{instance=~\"$node_name\", type=\"command\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Getmore Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Getmore Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"getmore\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Delete Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Delete Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"delete\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Insert Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Insert Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{instance=~\"$node_name\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"insert\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Update Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Update Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"update\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Query Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Query Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{ instance=~\"$node_name\", type=\"query\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Document Operations Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Top 5 Document Delete Operations",
   "type": "timeseries",
   "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"deleted\"}[5m]))))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "avg(rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"deleted\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Document Delete Operations",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"deleted\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 Document Insert Operations",
   "type": "timeseries",
   "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"inserted\"}[5m]))))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "avg(rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"inserted\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Document Insert Operations",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{instance=~\"$node_name\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{instance=~\"$node_name\",state=\"inserted\"}[5m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Document Return Operations",
   "type": "timeseries",
   "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"returned\"}[5m]))))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "avg(rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"returned\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Document Return Operations",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{instance=~\"$node_name\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{instance=~\"$node_name\",state=\"returned\"}[5m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Document Update Operations",
   "type": "timeseries",
   "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"updated\"}[5m]))))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "avg(rate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{ instance=~\"$node_name\",state=\"updated\"}[5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Document Update Operations",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{instance=~\"$node_name\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{instance=~\"$node_name\",state=\"updated\"}[5m]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Queued Operations Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Queued Read Operations",
     "type": "timeseries",
     "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((max_over_time(mongodb_mongod_global_lock_current_queue{ ervice_name=~\"$node_name\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"reader\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"reader\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Queued Read Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"reader\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Queued Write Operations",
     "type": "timeseries",
     "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((max_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"writer\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{ instance=~\"$node_name\",type=\"writer\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Queued Write Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mongodb_mongod_global_lock_current_queue{instance=~\"$node_name\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{instance=~\"$node_name\",type=\"writer\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}